### ISSUE TITLE
New release caused rename of Eisvogel.tex to Eisvogel.latex

### ISSUE THREAD

**Issue by pat-richter** [alexpovel/latex-extras-docker#2]
I've just run into this issue while working with your excellent image!

https://github.com/Wandmalfarbe/pandoc-latex-template/releases/tag/v2.0.0

This was just updated an hour ago...

**Comment by alexpovel** [comment]
Thanks for letting me know. I ran into this the other day and was made aware of the issue the hard way. This is now fixed in c0fabb59b7f1477824c0014f457bf056f8698830.

I'm a bit salty because I wasn't notified of your issue at all, only saw it now by chance. Would've fixed it immediately otherwise, without you needing to fork.

Happy to help for any future issues.

As an aside, maybe you're interested in [an example for how to employ this image for a CI/CD pipeline](https://collaborating.tuhh.de/alex/latex-git-cookbook) (tooting my own horn a bit here!).
